"""add triage and nursing fields to vital_signs

Revision ID: 1f691ed968eb
Revises: b7d4a4cbeda1
Create Date: 2026-07-19 19:04:37.216834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f691ed968eb'
down_revision = 'b7d4a4cbeda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_sugar', sa.Numeric(precision=4, scale=1), nullable=True))
        batch_op.add_column(sa.Column('pain_score', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('chief_complaint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration_of_illness', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('general_observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('urgency_level', sa.Enum('emergency', 'high', 'normal', 'low'), nullable=False))
        batch_op.add_column(sa.Column('nursing_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('nursing_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_column('nursing_notes')
        batch_op.drop_column('nursing_flags')
        batch_op.drop_column('urgency_level')
        batch_op.drop_column('general_observations')
        batch_op.drop_column('duration_of_illness')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('chief_complaint')
        batch_op.drop_column('pain_score')
        batch_op.drop_column('blood_sugar')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
