"""phase21: index patient search columns and audit_logs entity lookup

Revision ID: 7166ec7d00a3
Revises: 7244082c65d0
Create Date: 2026-07-09 13:08:57.468197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7166ec7d00a3'
down_revision = '7244082c65d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.DateTime(), nullable=True),
    sa.Column('clock_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'late', 'on_leave', 'half_day'), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_staff_attendance_user_date')
    )
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_user_id'), ['user_id'], unique=False)

    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('health_file_id', sa.Integer(), nullable=True),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('admitted_by', sa.Integer(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=True),
    sa.Column('admission_reason', sa.Text(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('expected_discharge_date', sa.Date(), nullable=True),
    sa.Column('actual_discharge_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('discharged_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('admitted', 'discharged', 'transferred'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['discharged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['health_file_id'], ['health_files.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_status'), ['status'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_phone'))
        batch_op.drop_index(batch_op.f('ix_patients_last_name'))
        batch_op.drop_index(batch_op.f('ix_patients_first_name'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity_type_entity_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_status'))
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))

    op.drop_table('admissions')
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendance_user_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_date'))

    op.drop_table('staff_attendance')
    # ### end Alembic commands ###
