"""phase20: add immunizations table

Revision ID: 7244082c65d0
Revises: a74d77151016
Create Date: 2026-07-05 22:26:26.568205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7244082c65d0'
down_revision = 'a74d77151016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immunizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=120), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('date_administered', sa.Date(), nullable=False),
    sa.Column('administered_by', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=60), nullable=True),
    sa.Column('site', sa.String(length=60), nullable=True),
    sa.Column('next_dose_due', sa.Date(), nullable=True),
    sa.Column('adverse_reaction', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['administered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('immunizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_immunizations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_immunizations_vaccine_name'), ['vaccine_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immunizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_immunizations_vaccine_name'))
        batch_op.drop_index(batch_op.f('ix_immunizations_patient_id'))

    op.drop_table('immunizations')
    # ### end Alembic commands ###
