"""Add queue_number and called_at to health_files, photo_data to patients, new patient_documents table

Revision ID: 910e57e19097
Revises: 7166ec7d00a3
Create Date: 2026-07-17 01:33:19.239061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910e57e19097'
down_revision = '7166ec7d00a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('health_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('called_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_data', sa.LargeBinary(length=16777215), nullable=True))
        batch_op.add_column(sa.Column('photo_mime', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('photo_mime')
        batch_op.drop_column('photo_data')

    with op.batch_alter_table('health_files', schema=None) as batch_op:
        batch_op.drop_column('called_at')
        batch_op.drop_column('queue_number')

    # ### end Alembic commands ###
