"""phase20: add drug_transactions ledger

Revision ID: 9c82aa72cbdd
Revises: af80c0bc16d8
Create Date: 2026-07-05 22:00:31.749979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c82aa72cbdd'
down_revision = 'af80c0bc16d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('received', 'dispensed', 'adjustment', 'disposal'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['drug_inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drug_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_transactions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_transactions_drug_id'), ['drug_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drug_transactions_transaction_type'), ['transaction_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_drug_transactions_drug_id'))
        batch_op.drop_index(batch_op.f('ix_drug_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_drug_transactions_batch_id'))

    op.drop_table('drug_transactions')
    # ### end Alembic commands ###
