"""phase20: add medical_certificates table

Revision ID: a74d77151016
Revises: 9c82aa72cbdd
Create Date: 2026-07-05 22:14:52.393438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74d77151016'
down_revision = '9c82aa72cbdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.Enum('sick_leave', 'fitness', 'medical_report', 'other'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked'), nullable=False),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_certificates_certificate_number'), ['certificate_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_medical_certificates_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_certificates_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_certificates_certificate_number'))

    op.drop_table('medical_certificates')
    # ### end Alembic commands ###
