"""phase20: add health_files table, link to vitals and consultations

Revision ID: af80c0bc16d8
Revises: 138d1e4d3447
Create Date: 2026-07-04 23:04:06.376633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af80c0bc16d8'
down_revision = '138d1e4d3447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - manually reordered, see note below ###
    op.create_table('health_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('with_mho', 'with_nurse', 'with_doctor', 'with_lab', 'with_pharmacy', 'closed'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_files_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_files_status'), ['status'], unique=False)

    # NOTE: reordered vs. the autogenerated version. We must drop the
    # consultations -> appointments foreign key BEFORE dropping the
    # appointments table itself (MySQL refuses to drop a table that's
    # still referenced by a live FK from another table). We also drop
    # 'appointments' with a single op.drop_table() instead of manually
    # dropping its indexes first — MySQL won't let you drop an index
    # that's backing a FK constraint, even on a table you're about to
    # delete outright. drop_table() removes indexes and constraints
    # together in one step, so there's nothing left to do by hand.
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_file_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_consultations_health_file_id'), ['health_file_id'], unique=False)
        batch_op.drop_constraint('consultations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'health_files', ['health_file_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('appointment_id')

    op.drop_table('appointments')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=mysql.ENUM('appointment', 'lab_result', 'low_stock', 'system', 'general', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('patient_flow', 'lab_result', 'low_stock', 'system', 'general'),
               existing_nullable=True)

    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_file_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vital_signs_health_file_id'), ['health_file_id'], unique=False)
        batch_op.create_foreign_key(None, 'health_files', ['health_file_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - reordered to mirror upgrade() ###
    with op.batch_alter_table('vital_signs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vital_signs_health_file_id'))
        batch_op.drop_column('health_file_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('notification_type',
               existing_type=sa.Enum('patient_flow', 'lab_result', 'low_stock', 'system', 'general'),
               type_=mysql.ENUM('appointment', 'lab_result', 'low_stock', 'system', 'general', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    op.create_table('appointments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('appointment_time', mysql.TIME(), nullable=False),
    sa.Column('reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'confirmed', 'checked_in', 'completed', 'cancelled', 'no_show'), nullable=False),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('booked_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], name=op.f('appointments_ibfk_1')),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name=op.f('appointments_ibfk_2')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('appointments_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consultations_ibfk_1'), 'appointments', ['appointment_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_consultations_health_file_id'))
        batch_op.drop_column('health_file_id')

    with op.batch_alter_table('health_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_files_status'))
        batch_op.drop_index(batch_op.f('ix_health_files_patient_id'))

    op.drop_table('health_files')
    # ### end Alembic commands ###