"""create drug interactions table

Revision ID: b157159e866f
Revises: 500ca8276c94
Create Date: 2026-08-04 00:07:53.300278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b157159e866f'
down_revision = '500ca8276c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_id_a', sa.Integer(), nullable=False),
    sa.Column('drug_id_b', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id_a'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug_id_b'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drug_id_a', 'drug_id_b', name='uq_drug_interaction_pair')
    )
    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.create_index('ix_drug_interaction_drug_a', ['drug_id_a'], unique=False)
        batch_op.create_index('ix_drug_interaction_drug_b', ['drug_id_b'], unique=False)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('drug_interactions', schema=None) as batch_op:
        batch_op.drop_index('ix_drug_interaction_drug_b')
        batch_op.drop_index('ix_drug_interaction_drug_a')

    op.drop_table('drug_interactions')
    # ### end Alembic commands ###
