"""add emergency_contact_relationship to patients

Revision ID: b7d4a4cbeda1
Revises: 910e57e19097
Create Date: 2026-07-18 21:06:28.930939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7d4a4cbeda1'
down_revision = '910e57e19097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('id_card', 'referral_letter', 'consent_form', 'medical_document', 'other'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime', sa.String(length=50), nullable=True),
    sa.Column('file_data', sa.LargeBinary(length=16777215), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_documents_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_address', sa.Text(), nullable=True))
        batch_op.alter_column('photo_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)
        batch_op.drop_column('emergency_contact_address')
        batch_op.drop_column('emergency_contact_relationship')

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_documents_patient_id'))

    op.drop_table('patient_documents')
    # ### end Alembic commands ###
