"""add is_pending_setup to lab_tests

Revision ID: be7becdb4104
Revises: 06b8767a2e2b
Create Date: 2026-07-24 11:25:27.707678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be7becdb4104'
down_revision = '06b8767a2e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pending_setup', sa.Boolean(), nullable=False))

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=mysql.MEDIUMBLOB(),
               type_=sa.LargeBinary(length=16777215),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('photo_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('patient_documents', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(length=16777215),
               type_=mysql.MEDIUMBLOB(),
               existing_nullable=False)

    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.drop_column('is_pending_setup')

    # ### end Alembic commands ###
